steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zeta-ascent-272907/a2sv/Hack/Backend:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/zeta-ascent-272907/a2sv/Hack/Backend:$SHORT_SHA']